rails_app/config/routes.rb
Rails.application.routes.draw do

  #namespace :user_manager do
  #resources :groups
  #  resources :users
  # resources :membershiplevels
  # get 'users/:id/pin_generator' => 'users#pin_generator', as: :pin_generator
  # patch 'users/:id/generate_pin' => 'users#generate_pin', as: :generate_pin
  # get 'membershiplevels/:id/edit_users' => 'membershiplevels#edit_users', as: :membershiplevels_edit_users
  # get 'membershiplevels/:id/show_users' => 'membershiplevels#show_users', as: :membershiplevels_show_users
  # patch 'membershiplevels/:id/update_users' => "membershiplevels#update_users", as: :membershiplevels_update_users
  #end

  post "toggle_left_nav_drawer" => "layouts#toggle_left_nav_drawer", as: :toggle_left_nav_drawer

  namespace :user_manager do
    resources :groups do
      resources :membershiplevels, except: [:index, :show]
    end
    resources :users do
      get 'pin_generator' => 'users#pin_generator', as: :pin_generator
      patch 'generate_pin' => 'users#generate_pin', as: :generate_pin
    end
    resources :apps do
      resources :roles
    end
  end

  namespace :media_time do
    resources :media_times
    get 'media_global_setting' => 'media_global_settings#show'
    get 'media_global_setting/edit' => 'media_global_settings#edit'
    patch 'media_global_setting.1' => 'media_global_settings#update'
    post 'logins/toggle' => 'logins#toggle_login', as: :logins_toggle
    get 'logins/login_display' => 'logins#login_display', as: :login_display
  end

  namespace :rulebook do
    resources :decision_making_units
    resources :rule_categories
    resources :rule_types
    resources :rules do
      resources :rule_contents
    end
  end

  resources :rooms

  devise_for :users, controllers: {
    sessions: 'devise_users/sessions'
  }
  root to: 'pages#home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

rails_app/app/models/rulebook/decision_making_unit.rb
class DecisionMakingUnit < ApplicationRecord
  has_and_belongs_to_many :groups

  scope :ordered, -> {order(name: :asc)}

end

rails_app/app/models/rulebook/joins/rooms_rule.rb
class RoomsRule < ApplicationRecord
  belongs_to :rule
  belongs_to :room
end

rails_app/app/models/rulebook/joins/rule_categories_rule.rb
class RuleCategoriesRule < ApplicationRecord
  belongs_to :rule_category
  belongs_to :rule
end

rails_app/app/models/rulebook/joins/rule_types_rule.rb
class RuleTypesRule < ApplicationRecord
  belongs_to :rule_type
  belongs_to :rule
end

rails_app/app/models/rulebook/rule.rb
class Rule < ApplicationRecord
  has_many :rule_categories_rules
  has_many :rule_categories, through: :rule_categories_rules
  has_many :rule_types_rules
  has_many :rule_types, through: :rule_types_rules
  has_many :rooms_rules
  has_many :rooms, through: :rooms_rules


  has_many :rule_contents

  scope :ordered, -> {order(id: :asc)}

end

rails_app/app/models/rulebook/rule_category.rb
class RuleCategory < ApplicationRecord
  has_many :rule_categories_rules
  has_many :rules, through: :rule_categories_rules

  scope :ordered, -> {order(name: :asc)}

end

rails_app/app/models/rulebook/rule_content.rb
class RuleContent < ApplicationRecord
  belongs_to :rule

  scope :ordered, -> {order(name: :asc)}

end

rails_app/app/models/rulebook/rule_type.rb
class RuleType < ApplicationRecord
  has_many :rule_types_rules
  has_many :rules, through: :rule_types_rules
  scope :ordered, -> {order(name: :asc)}

end

rails_app/app/controllers/rulebook/decision_making_units_controller.rb
class Rulebook::DecisionMakingUnitsController < ApplicationController
  before_action :set_decision_making_unit, only: [:show, :edit, :update, :destroy]
  def index
    @decision_making_units = DecisionMakingUnit.ordered
    skip_authorization
  end

  def show
    skip_authorization
  end

  def new
    @decision_making_unit = DecisionMakingUnit.new
    authorize @decision_making_unit
  end

  def create
    @decision_making_unit = DecisionMakingUnit.new(decision_making_unit_params)
    authorize @decision_making_unit
    if @decision_making_unit.save
      respond_to do |format|
        format.html  { redirect_to rulebook_decision_making_units_path, notice: "DecisionMakingUnit was successfully created." }
        format.turbo_stream { flash.now[:notice] = "DecisionMakingUnit was successfully created." }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize @decision_making_unit
  end

  def update
    authorize @decision_making_unit
    if @decision_making_unit.update(decision_making_unit_params)
      respond_to do |format|
        format.html { redirect_to rulebook_decision_making_units_path, notice: "DecisionMakingUnit was successfully updated." }
        format.turbo_stream { flash.now[:notice] = "DecisionMakingUnit was successfully updated." }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @decision_making_unit
    @decision_making_unit.destroy
    respond_to do |format|
      format.html { redirect_to rulebook_decision_making_units_path, notice: 'Gruppe wurde gelöscht!' }
      format.turbo_stream { flash.now[:notice] = "Gruppe wurde gelöscht!" }
    end
  end

  private

  def set_decision_making_unit
    @decision_making_unit = DecisionMakingUnit.find(params[:id])
  end

  def decision_making_unit_params
    params.require(:decision_making_unit).permit(:name)
  end
end

rails_app/app/controllers/rulebook/rule_categories_controller.rb
class Rulebook::RuleCategoriesController < ApplicationController
  before_action :set_rule_category, only: [:show, :edit, :update, :destroy]
  def index
    @rule_categories = RuleCategory.ordered
    skip_authorization
  end

  def show
    skip_authorization
  end

  def new
    @rule_category = RuleCategory.new
    authorize @rule_category
  end

  def create
    @rule_category = RuleCategory.new(rule_category_params)
    authorize @rule_category
    if @rule_category.save
      respond_to do |format|
        format.html  { redirect_to rulebook_rule_categories_path, notice: "RuleCategory was successfully created." }
        format.turbo_stream { flash.now[:notice] = "RuleCategory was successfully created." }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize @rule_category
  end

  def update
    authorize @rule_category
    if @rule_category.update(rule_category_params)
      respond_to do |format|
        format.html { redirect_to rulebook_rule_categories_path, notice: "RuleCategory was successfully updated." }
        format.turbo_stream { flash.now[:notice] = "RuleCategory was successfully updated." }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @rule_category
    @rule_category.destroy
    respond_to do |format|
      format.html { redirect_to rulebook_rule_categories_path, notice: 'Regel Kategorie wurde gelöscht!' }
      format.turbo_stream { flash.now[:notice] = "Regel Kategorie wurde gelöscht!" }
    end
  end

  private

  def set_rule_category
    @rule_category = RuleCategory.find(params[:id])
  end

  def rule_category_params
    params.require(:rule_category).permit(:name)
  end
end

rails_app/app/controllers/rulebook/rule_types_controller.rb
class Rulebook::RuleTypesController < ApplicationController
  before_action :set_rule_type, only: [:show, :edit, :update, :destroy]
  def index
    @rule_types = RuleType.ordered
    skip_authorization
  end

  def show
    skip_authorization
  end

  def new
    @rule_type = RuleType.new
    authorize @rule_type
  end

  def create
    @rule_type = RuleType.new(rule_type_params)
    authorize @rule_type
    if @rule_type.save
      respond_to do |format|
        format.html  { redirect_to rulebook_rule_types_path, notice: "RuleType was successfully created." }
        format.turbo_stream { flash.now[:notice] = "RuleType was successfully created." }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize @rule_type
  end

  def update
    authorize @rule_type
    if @rule_type.update(rule_type_params)
      respond_to do |format|
        format.html { redirect_to rulebook_rule_types_path, notice: "RuleType was successfully updated." }
        format.turbo_stream { flash.now[:notice] = "RuleType was successfully updated." }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @rule_type
    @rule_type.destroy
    respond_to do |format|
      format.html { redirect_to rulebook_rule_types_path, notice: 'RegelTyp wurde gelöscht!' }
      format.turbo_stream { flash.now[:notice] = "RegelTyp wurde gelöscht!" }
    end
  end

  private

  def set_rule_type
    @rule_type = RuleType.find(params[:id])
  end

  def rule_type_params
    params.require(:rule_type).permit(:name)
  end
end

rails_app/app/controllers/rulebook/rules_controller.rb
class Rulebook::RulesController < ApplicationController
  before_action :set_rule, only: [:show, :edit, :update, :destroy]
  def index
    @rules = Rule.ordered
    skip_authorization
  end

  def show
    skip_authorization
  end

  def new
    @rule = Rule.new
    authorize @rule
  end

  def create
    @rule = Rule.new(rule_params)
    authorize @rule
    if @rule.save
      respond_to do |format|
        format.html  { redirect_to rulebook_rules_path, notice: "Rule was successfully created." }
        format.turbo_stream { flash.now[:notice] = "Rule was successfully created." }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize @rule
  end

  def update
    authorize @rule
    if @rule.update(rule_params)
      respond_to do |format|
        format.html { redirect_to rulebook_rules_path, notice: "Rule was successfully updated." }
        format.turbo_stream { flash.now[:notice] = "Rule was successfully updated." }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @rule
    @rule.destroy
    respond_to do |format|
      format.html { redirect_to rulebook_rules_path, notice: 'Regel wurde gelöscht!' }
      format.turbo_stream { flash.now[:notice] = "Regel wurde gelöscht!" }
    end
  end

  private

  def set_rule
    @rule = Rule.find(params[:id])
  end

  def rule_params
    params.require(:rule).permit(:title)
  end
end

rails_app/app/helpers/rulebook/decision_making_units_helper.rb
module Rulebook::DecisionMakingUnitsHelper
end

rails_app/app/helpers/rulebook/rule_categories_helper.rb
module Rulebook::RuleCategoriesHelper
end

rails_app/app/helpers/rulebook/rule_types_helper.rb
module Rulebook::RuleTypesHelper
end

rails_app/app/helpers/rulebook/rules_helper.rb
module Rulebook::RulesHelper
end

rails_app/app/views/rulebook/rules/_empty_state.html.erb
<div class="empty-state empty-state--only-child">
  <p class="empty-state__text">
    Es gibt noch keine Regeln!
  </p>

  <%= link_to "Regel hinzufügen", new_rulebook_rule_path, class: "btn btn-green", data: { turbo_frame: dom_id(Rule.new) } %>
</div>

rails_app/app/views/rulebook/rules/_form.html.erb
<%= simple_form_for [:rulebook, rule], html: {clasS: "form"} do |f| %>
   <div class="card-content" >
     <%= form_error_notification(rule) %>
     <div class="list-item">
       <%= f.input :title, input_html: { autofocus: true } %>
       <div class="list-item-append">
         <%= link_to icon("fa-solid", "xmark"), rulebook_rules_path, class: "btn btn-red mr-2" %>
         <%= button_tag icon("fa-solid", "floppy-disk"), type: "submit", class: "btn btn-green"  %>
       </div>
     </div>

   </div>



<% end %>

rails_app/app/views/rulebook/rules/_rule.html.erb
<%= turbo_frame_tag rule do %>
  <div class="card">
    <div class="card-content">
      <div class="list-item">
        <%= link_to rule.title.titleize, rulebook_rule_path(rule), data: { turbo_frame: "_top" } %>
        <div class="list-item-append">
          <% if policy(rule).destroy? %>
            <%= button_to icon('fa-solid', 'trash', class:"fa-1x"), rulebook_rule_path(rule),form: { data: { turbo_confirm: "Möchtest du die Regel #{rule.title.titleize} wirklich löschen?" } }, method: :delete, class: "btn btn-red mr-2"%>
          <% end %>
          <% if policy(rule).update? %>
            <%= link_to icon('fa-solid', 'pen-to-square', class:"fa-1x"), edit_rulebook_rule_path(rule), class: "btn btn-yellow" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

rails_app/app/views/rulebook/rules/create.turbo_stream.erb
<%= turbo_stream.prepend "rules", partial: @rule %>
<%= turbo_stream.update Rule.new, "" %>
<%= render_turbo_stream_flash_messages %>

rails_app/app/views/rulebook/rules/destroy.turbo_stream.erb
<%= turbo_stream.remove @rule %>
<%= render_turbo_stream_flash_messages %>

rails_app/app/views/rulebook/rules/edit.html.erb
<%= link_to sanitize("&larr; Zurück zu Regeln"), rulebook_rules_path %>
<div class="container-title">
  <h1> Regel bearbeiten </h1>
</div>
<div class="container-content">
  <%= turbo_frame_tag @rule do %>
    <div class="card">
      <%= render "form", rule: @rule %>
    </div>
  <% end %>
</div>

rails_app/app/views/rulebook/rules/index.html.erb
<%= turbo_stream_from "rules" %>
<div class="container-title">
  <h1>Regeln</h1>
  <% if policy(Rule.new).create? %>
    <%= link_to icon("fa-solid", "plus", "Regel hinzufügen", class: "fa-1x"),
                new_rulebook_rule_path,
                class: "btn btn-green",
                data: { turbo_frame: dom_id(Rule.new) }%>
  <% end %>
</div>
<div class="container-content">
  <%= turbo_frame_tag Rule.new %>
  <%= turbo_frame_tag "rules" do %>
    <%= render "rulebook/rules/empty_state" %>
    <%= render @rules %>
  <% end %>
</div>

rails_app/app/views/rulebook/rules/new.html.erb
<%= link_to sanitize("&larr; Zurück zu Regeln"), rulebook_rules_path %>
<div class="container-title">
  <h1> Neue Regel </h1>
</div>
<%= turbo_frame_tag @rule do %>
  <div class="card">
  <%= render "form", rule: @rule %>
  </div>
<% end %>

rails_app/app/views/rulebook/rules/show.html.erb
<%= link_to sanitize("&larr; Zurück zu Regeln"), rulebook_rules_path %>
<div class="container-title">
  To be announced.... Watch some kitten videos instead!

</div>

rails_app/app/views/rulebook/rules/update.turbo_stream.erb
<%= turbo_stream.replace @rule %>
<%= render_turbo_stream_flash_messages %>