rails_app/config/routes.rb
Rails.application.routes.draw do

  #namespace :user_manager do
  #resources :groups
  #  resources :users
  # resources :membershiplevels
  # get 'users/:id/pin_generator' => 'users#pin_generator', as: :pin_generator
  # patch 'users/:id/generate_pin' => 'users#generate_pin', as: :generate_pin
  # get 'membershiplevels/:id/edit_users' => 'membershiplevels#edit_users', as: :membershiplevels_edit_users
  # get 'membershiplevels/:id/show_users' => 'membershiplevels#show_users', as: :membershiplevels_show_users
  # patch 'membershiplevels/:id/update_users' => "membershiplevels#update_users", as: :membershiplevels_update_users
  #end

  post "toggle_left_nav_drawer" => "layouts#toggle_left_nav_drawer", as: :toggle_left_nav_drawer

  namespace :user_manager do
    resources :groups do
      resources :membershiplevels, except: [:index, :show]
    end
    resources :users do
      get 'pin_generator' => 'users#pin_generator', as: :pin_generator
      patch 'generate_pin' => 'users#generate_pin', as: :generate_pin
    end
    resources :apps do
      resources :roles
    end
  end

  namespace :media_time do
    resources :media_times
    get 'media_global_setting' => 'media_global_settings#show'
    get 'media_global_setting/edit' => 'media_global_settings#edit'
    patch 'media_global_setting.1' => 'media_global_settings#update'
    post 'logins/toggle' => 'logins#toggle_login', as: :logins_toggle
    get 'logins/login_display' => 'logins#login_display', as: :login_display
  end

  namespace :rulebook do
    resources :decision_making_units
    resources :rule_categories
    resources :rule_types
    resources :rules do
      resources :rule_contents
    end
  end

  resources :rooms

  devise_for :users, controllers: {
    sessions: 'devise_users/sessions'
  }
  root to: 'pages#home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

rails_app/app/models/permissions/group.rb
class Group < ApplicationRecord
    validates :name, presence: true, allow_blank: false, uniqueness: true
    has_many :membershiplevels, dependent: :destroy
    has_many :users, through: :membershiplevels
    has_and_belongs_to_many :decision_making_units
    after_create :add_basic_membershiplevel
    after_create_commit -> { broadcast_prepend_later_to "groups", partial: "user_manager/groups/group", locals: { group: self }, target: "groups" }
    after_update_commit -> { broadcast_update_later_to "groups", partial: "user_manager/groups/group", locals: { group: self }, target: self }
    after_destroy_commit -> { broadcast_remove_to "groups", target: self }

    def add_basic_membershiplevel
        self.membershiplevels.create({:name => "basic"})
        self.set_default_membershiplevel
    end

    def set_default_membershiplevel(id=0)
        level = self.membershiplevels.where(:id => id).first || self.default_membershiplevel || self.membershiplevels.first
        self.default_membershiplevel_id = level.id
        self.save
    end

    def default_membershiplevel
        self.membershiplevels.where(:id => self.default_membershiplevel_id).first
    end

    def users_count
        self.users.uniq.count
    end

    def previous_group
        Group.ordered.where("name < ?", name).last
    end

    scope :ordered, -> {order(name: :asc)}
end

rails_app/app/controllers/user_manager/apps_controller.rb
class UserManager::AppsController < ApplicationController
  before_action :set_app, only: [:show, :edit, :update]
  include Pundit::Authorization
  after_action :verify_authorized

  def index
    @apps = App.ordered
    skip_authorization
  end

  def show
    skip_authorization
    @roles = @app.roles.ordered
  end

  def edit
    authorize @app
  end

  def update
    authorize @app
    if @app.update(app_params)
      respond_to do |format|
        format.html { redirect_to user_manager_apps_path, notice: "App was successfully updated." }
        format.turbo_stream { flash.now[:notice] = "App was successfully updated." }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end


  private

  def set_app
    @app = App.find(params[:id])
  end

  def app_params
    params.require(:app).permit(:name, :active)
  end
end

rails_app/app/controllers/user_manager/groups_controller.rb
class UserManager::GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  def index
    @groups = Group.ordered
    skip_authorization
  end

  def show
    skip_authorization
    @membershiplevels = @group.membershiplevels.ordered
  end

  def new
    @group = Group.new
    authorize @group
  end

  def create
    @group = Group.new(group_params)
    authorize @group
    if @group.save
      respond_to do |format|
        format.html  { redirect_to user_manager_groups_path, notice: "Group was successfully created." }
        format.turbo_stream { flash.now[:notice] = "Group was successfully created." }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize @group
  end

  def update
    authorize @group
    if @group.update(group_params)
      respond_to do |format|
        format.html { redirect_to user_manager_groups_path, notice: "Group was successfully updated." }
        format.turbo_stream { flash.now[:notice] = "Group was successfully updated." }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @group
    @group.destroy
    respond_to do |format|
      format.html { redirect_to user_manager_groups_path, notice: 'Gruppe wurde gelöscht!' }
      format.turbo_stream { flash.now[:notice] = "Gruppe wurde gelöscht!" }
    end
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:name)
  end
end

rails_app/app/controllers/user_manager/membershiplevels_controller.rb
class UserManager::MembershiplevelsController < ApplicationController
  before_action :set_group
  before_action :set_membershiplevel, only: [:edit, :update, :destroy]
  before_action :set_new_membershiplevel, only: :new
  before_action :build_membershiplevel_from_params, only: [:create]
  before_action :set_multiselect_data, only: [:edit, :new, :create, :update]
  include Pundit::Authorization
  after_action :verify_authorized

  def new
    authorize @membershiplevel
  end

  def create
    authorize @membershiplevel
    if @membershiplevel.save
      respond_to do |format|
        format.html { redirect_to user_manager_group_path(@group), notice: "Mitgliedschaftslevel erstellt" }
        format.turbo_stream { flash.now[:notice] = "Mitgliedschaftslevel erstellt" }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize @membershiplevel
  end

  def update
    authorize @membershiplevel
    if @membershiplevel.update(membershiplevel_params)
      respond_to do |format|
        format.html { redirect_to user_manager_group_path(@group), notice: "Mitgliedschaftslevel geändert" }
        format.turbo_stream { flash.now[:notice] = "Mitgliedschaftslevel geändert" }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @membershiplevel
      @membershiplevel.destroy
      respond_to do |format|
        format.html { redirect_to user_manager_group_path(@group), notice: "Mitgliedschaftslevel gelöscht" }
        format.turbo_stream { flash.now[:notice] = "Mitgliedschaftslevel gelöscht" }
      end
  end

  private

  def set_new_membershiplevel
    @membershiplevel = @group.membershiplevels.build
  end

  def build_membershiplevel_from_params
    @membershiplevel = @group.membershiplevels.build(membershiplevel_params)
  end
  def set_multiselect_data
    @users = User.all.sort_by { |a| [@membershiplevel.users.include?(a) ? 0 : 1 , a.name]} # Fetch users once
    @multiselect_users_elements_value = @users.map { |u| "membershiplevel_#{@membershiplevel.id}_user_ids_#{u.id}" }.to_json
    @multiselect_users_names_value = @users.map { |u| u.name.titleize }.to_json
    @roles = Role.all.sort_by { |a| [@membershiplevel.roles.include?(a) ? 0 : 1 , a.name]} # Fetch users once
    @multiselect_roles_elements_value = @roles.map { |r| "membershiplevel_#{@membershiplevel.id}_role_ids_#{r.id}" }.to_json
    @multiselect_roles_names_value = @roles.map { |r| r.name.titleize }.to_json
  end
  def set_group
    @group = Group.find(params[:group_id])
  end

  def set_membershiplevel
    @membershiplevel = Membershiplevel.find(params[:id])
  end

  def membershiplevel_params
    params.require(:membershiplevel).permit(:name, :user_ids => [], :role_ids => [])
  end
end

rails_app/app/controllers/user_manager/roles_controller.rb
class UserManager::RolesController < ApplicationController
  before_action :set_app
  before_action :set_role, only: [:edit, :update, :destroy]
  before_action :set_new_role, only: :new
  before_action :build_role_from_params, only: [:create]
  before_action :set_multiselect_data, only: [:edit, :new, :create, :update]
  include Pundit::Authorization
  after_action :verify_authorized

  def new
    authorize @role
  end

  def create
    authorize @role
    if @role.save
      respond_to do |format|
        format.html { redirect_to user_manager_app_path(@app), notice: "Rolle erstellt" }
        format.turbo_stream { flash.now[:notice] = "Rolle erstellt" }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize @role
  end

  def update
    authorize @role
    if @role.update(role_params)
      respond_to do |format|
        format.html { redirect_to user_manager_app_path(@app), notice: "Rolle geändert" }
        format.turbo_stream { flash.now[:notice] = "Rolle geändert" }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @role
    @role.destroy
    respond_to do |format|
      format.html { redirect_to user_manager_app_path(@app), notice: "Rolle gelöscht" }
      format.turbo_stream { flash.now[:notice] = "Rolle gelöscht" }
    end
  end

  private

  def set_new_role
    @role = @app.roles.build
  end

  def build_role_from_params
    @role = @app.roles.build(role_params)
  end
  def set_multiselect_data
    @permissions = @app.permissions.ordered# Fetch users once
    @multiselect_permissions_elements_value = @permissions.map { |r| "role_#{@role.id}_permission_ids_#{r.id}" }.to_json
    @multiselect_permissions_names_value = @permissions.map { |r| r.name.titleize }.to_json
  end

  def set_app
    @app = App.find(params[:app_id])
  end

  def set_role
    @role = Role.find(params[:id])
  end

  def role_params
    params.require(:role).permit(:name, :permission_ids => [])
  end
end

rails_app/app/controllers/user_manager/users_controller.rb
class UserManager::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :pin_generator, :generate_pin]
  include Pundit::Authorization
  after_action :verify_authorized

  def index
    @users = User.ordered
    authorize @users
  end

  def show
    authorize @user
    @membershiplevels = @user.membershiplevels.ordered
  end

  def new
    @user = User.new
    authorize @user
  end

  def create
    @user = User.new(user_params)
    authorize @user
    if @user.save
      respond_to do |format|
        format.html  { redirect_to user_manager_users_path, notice: "User was successfully created." }
        format.turbo_stream { flash.now[:notice] = "User was successfully created." }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize @user
  end

  def pin_generator
    authorize @user
    @pin = @user.generate_pin
  end

  def generate_pin
    authorize @user
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_manager_pin_generator_url(@user), notice: "User was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize @user
    if @user.update(user_params)
      respond_to do |format|
        format.html { redirect_to user_manager_users_path, notice: "User was successfully updated." }
        format.turbo_stream { flash.now[:notice] = "User was successfully updated." }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @user
    @user.destroy
    respond_to do |format|
      format.html { redirect_to user_manager_users_path, notice: 'User wurde gelöscht!' }
      format.turbo_stream { flash.now[:notice] = "User wurde gelöscht!" }
    end
  end

  private

  def set_user

    @user = User.find(params[:id])
  end

  def user_params
    if params[:user][:password].blank? && params[:user][:password_confirmation].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end
    params.require(:user).permit(:name, :avatar, :password, :password_confirmation, :pin, :easy_pin, :pin_length)
  end
end

rails_app/app/controllers/user_manager_old/groups_controller.rb
#docker exec -it dst_rails_dev rails g scaffold_controller user_manager::group name --model-name="Group"
class UserManager::GroupsController < ApplicationController
  before_action :set_group, only: %i[ show edit update destroy ]

  # GET /user_manager/groups or /user_manager/groups.json
  def index
    @groups = Group.all
  end

  # GET /user_manager/groups/1 or /user_manager/groups/1.json
  def show
  end

  # GET /user_manager/groups/new
  def new
    @group = Group.new
  end

  # GET /user_manager/groups/1/edit
  def edit
  end

  # POST /user_manager/groups or /user_manager/groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to user_manager_group_url(@group), notice: "Group was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_manager/groups/1 or /user_manager/groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to user_manager_group_url(@group), notice: "Group was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_manager/groups/1 or /user_manager/groups/1.json
  def destroy
    @group.destroy!

    respond_to do |format|
      format.html { redirect_to user_manager_groups_url, notice: "Group was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def group_params
      params.require(:group).permit(:name)
    end
end

rails_app/app/helpers/user_manager/apps_helper.rb
module UserManager::AppsHelper
end

rails_app/app/helpers/user_manager/groups_helper.rb
module UserManager::GroupsHelper
end

rails_app/app/helpers/user_manager/membershiplevels_helper.rb
module UserManager::MembershiplevelsHelper
end

rails_app/app/helpers/user_manager/roles_helper.rb
module UserManager::RolesHelper
end

rails_app/app/helpers/user_manager/users_helper.rb
module UserManager::UsersHelper
end

rails_app/app/views/user_manager/groups/_empty_state.html.erb
<div class="empty-state empty-state--only-child">
  <p class="empty-state__text">
    Es gibt noch keine Gruppen!
  </p>

  <%= link_to "Gruppe hinzufügen", new_user_manager_group_path, class: "btn btn-green", data: { turbo_frame: dom_id(Group.new) } %>
</div>

rails_app/app/views/user_manager/groups/_form.html.erb
<%= simple_form_for [:user_manager, group], html: {clasS: "form"} do |f| %>
   <div class="card-content" >
     <%= form_error_notification(group) %>
     <div class="list-item">
       <%= f.input :name, input_html: { autofocus: true } %>
       <div class="list-item-append">
         <%= link_to icon("fa-solid", "xmark"), user_manager_groups_path, class: "btn btn-red mr-2" %>
         <%= button_tag icon("fa-solid", "floppy-disk"), type: "submit", class: "btn btn-green"  %>
       </div>
     </div>

   </div>



<% end %>

rails_app/app/views/user_manager/groups/_group.html.erb
<%= turbo_frame_tag group do %>
  <div class="card">
    <div class="card-content">
      <div class="list-item">
        <%= link_to group.name.titleize, user_manager_group_path(group), data: { turbo_frame: "_top" } %>
        <div class="list-item-append">
          <% if policy(group).destroy? %>
            <%= button_to icon('fa-solid', 'trash', class:"fa-1x"), user_manager_group_path(group),form: { data: { turbo_confirm: "Möchtest du die Gruppe #{group.name.titleize} wirklich löschen?" } }, method: :delete, class: "btn btn-red mr-2"%>
          <% end %>
          <% if policy(group).update? %>
            <%= link_to icon('fa-solid', 'pen-to-square', class:"fa-1x"), edit_user_manager_group_path(group), class: "btn btn-yellow" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

rails_app/app/views/user_manager/groups/create.turbo_stream.erb
<%= turbo_stream.prepend "groups", partial: @group %>
<%= turbo_stream.update Group.new, "" %>
<%= render_turbo_stream_flash_messages %>

rails_app/app/views/user_manager/groups/destroy.turbo_stream.erb
<%= turbo_stream.remove @group %>
<%= render_turbo_stream_flash_messages %>

rails_app/app/views/user_manager/groups/edit.html.erb
<%= link_to sanitize("&larr; Zurück zu Gruppen"), user_manager_groups_path %>
<div class="container-title">
  <h1> Gruppe bearbeiten </h1>
</div>
<div class="container-content">
  <%= turbo_frame_tag @group do %>
    <div class="card">
      <%= render "form", group: @group %>
    </div>
  <% end %>
</div>

rails_app/app/views/user_manager/groups/index.html.erb
<%= turbo_stream_from "groups" %>
<div class="container-title">
  <h1>Gruppen</h1>
  <% if policy(Group.new).create? %>
    <%= link_to icon("fa-solid", "plus", "Gruppe hinzufügen", class: "fa-1x"),
                new_user_manager_group_path,
                class: "btn btn-green",
                data: { turbo_frame: dom_id(Group.new) }%>
  <% end %>
</div>
<div class="container-content">
  <%= turbo_frame_tag Group.new %>
  <%= turbo_frame_tag "groups" do %>
    <%= render "user_manager/groups/empty_state" %>
    <%= render @groups %>
  <% end %>
</div>

rails_app/app/views/user_manager/groups/new.html.erb
<%= link_to sanitize("&larr; Zurück zu Gruppen"), user_manager_groups_path %>
<div class="container-title">
  <h1> Neue Gruppe </h1>
</div>
<%= turbo_frame_tag @group do %>
  <div class="card">
  <%= render "form", group: @group %>
  </div>
<% end %>

rails_app/app/views/user_manager/groups/show.html.erb
<%= link_to sanitize("&larr; Zurück zu Gruppen"), user_manager_groups_path %>
<div class="container-title">
  <h1><%= @group.name %></h1>
  <% if policy(Membershiplevel.new).create? %>
    <%= link_to "Neues Mitgliedschaftslevel",
                new_user_manager_group_membershiplevel_path(@group),
                data: { turbo_frame: dom_id(Membershiplevel.new)},
                class: "btn btn-green" %>
  <% end %>
</div>
<div class="container-content">

  <%= turbo_frame_tag Membershiplevel.new %>
  <%= turbo_frame_tag "membershiplevels" do %>
    <%= render @membershiplevels, group: @group %>
  <% end %>
</div>

rails_app/app/views/user_manager/groups/update.turbo_stream.erb
<%= turbo_stream.replace @group %>
<%= render_turbo_stream_flash_messages %>