rails_app/config/routes.rb
Rails.application.routes.draw do

  #namespace :user_manager do
  #resources :groups
  #  resources :users
  # resources :membershiplevels
  # get 'users/:id/pin_generator' => 'users#pin_generator', as: :pin_generator
  # patch 'users/:id/generate_pin' => 'users#generate_pin', as: :generate_pin
  # get 'membershiplevels/:id/edit_users' => 'membershiplevels#edit_users', as: :membershiplevels_edit_users
  # get 'membershiplevels/:id/show_users' => 'membershiplevels#show_users', as: :membershiplevels_show_users
  # patch 'membershiplevels/:id/update_users' => "membershiplevels#update_users", as: :membershiplevels_update_users
  #end

  post "toggle_left_nav_drawer" => "layouts#toggle_left_nav_drawer", as: :toggle_left_nav_drawer

  namespace :user_manager do
    resources :groups do
      resources :membershiplevels, except: [:index, :show]
    end
    resources :users do
      get 'pin_generator' => 'users#pin_generator', as: :pin_generator
      patch 'generate_pin' => 'users#generate_pin', as: :generate_pin
    end
    resources :apps do
      resources :roles
    end
  end

  namespace :media_time do
    resources :media_times
    get 'media_global_setting' => 'media_global_settings#show'
    get 'media_global_setting/edit' => 'media_global_settings#edit'
    patch 'media_global_setting.1' => 'media_global_settings#update'
    post 'logins/toggle' => 'logins#toggle_login', as: :logins_toggle
    get 'logins/login_display' => 'logins#login_display', as: :login_display
  end

  namespace :rulebook do
    resources :decision_making_units
    resources :rule_categories
    resources :rule_types
    resources :rules do
      resources :rule_contents
    end
  end

  resources :rooms

  devise_for :users, controllers: {
    sessions: 'devise_users/sessions'
  }
  root to: 'pages#home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

rails_app/app/models/room.rb
class Room < ApplicationRecord
  has_many :room_rules
  has_many :rules, through: :room_rules

  scope :ordered, -> {order(name: :asc)}

end

rails_app/app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]
  def index
    @rooms = Room.ordered
    skip_authorization
  end

  def show
    skip_authorization
  end

  def new
    @room = Room.new
    authorize @room
  end

  def create
    @room = Room.new(room_params)
    authorize @room
    if @room.save
      respond_to do |format|
        format.html  { redirect_to rooms_path, notice: "Room was successfully created." }
        format.turbo_stream { flash.now[:notice] = "Room was successfully created." }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize @room
  end

  def update
    authorize @room
    if @room.update(room_params)
      respond_to do |format|
        format.html { redirect_to rooms_path, notice: "Room was successfully updated." }
        format.turbo_stream { flash.now[:notice] = "Room was successfully updated." }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @room
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_path, notice: 'Raum wurde gelöscht!' }
      format.turbo_stream { flash.now[:notice] = "Raum wurde gelöscht!" }
    end
  end

  private

  def set_room
    @room = Room.find(params[:id])
  end

  def room_params
    params.require(:room).permit(:name)
  end
end

rails_app/app/helpers/rooms_helper.rb
module RoomsHelper
end

rails_app/app/views/rooms/_empty_state.html.erb
<div class="empty-state empty-state--only-child">
  <p class="empty-state__text">
    Es gibt noch keine Räume!
  </p>

  <%= link_to "Raum hinzufügen", new_room_path, class: "btn btn-green", data: { turbo_frame: dom_id(Room.new) } %>
</div>

rails_app/app/views/rooms/_form.html.erb
<%= simple_form_for room, html: {clasS: "form"} do |f| %>
   <div class="card-content" >
     <%= form_error_notification(room) %>
     <div class="list-item">
       <%= f.input :name, input_html: { autofocus: true } %>
       <div class="list-item-append">
         <%= link_to icon("fa-solid", "xmark"), rooms_path, class: "btn btn-red mr-2" %>
         <%= button_tag icon("fa-solid", "floppy-disk"), type: "submit", class: "btn btn-green"  %>
       </div>
     </div>

   </div>



<% end %>

rails_app/app/views/rooms/_room.html.erb
<%= turbo_frame_tag room do %>
  <div class="card">
    <div class="card-content">
      <div class="list-item">
        <%= link_to room.name.titleize, room_path(room), data: { turbo_frame: "_top" } %>
        <div class="list-item-append">
          <% if policy(room).destroy? %>
            <%= button_to icon('fa-solid', 'trash', class:"fa-1x"), room_path(room),form: { data: { turbo_confirm: "Möchtest du die Raum #{room.name.titleize} wirklich löschen?" } }, method: :delete, class: "btn btn-red mr-2"%>
          <% end %>
          <% if policy(room).update? %>
            <%= link_to icon('fa-solid', 'pen-to-square', class:"fa-1x"), edit_room_path(room), class: "btn btn-yellow" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

rails_app/app/views/rooms/create.turbo_stream.erb
<%= turbo_stream.prepend "rooms", partial: @room %>
<%= turbo_stream.update Room.new, "" %>
<%= render_turbo_stream_flash_messages %>

rails_app/app/views/rooms/destroy.turbo_stream.erb
<%= turbo_stream.remove @room %>
<%= render_turbo_stream_flash_messages %>

rails_app/app/views/rooms/edit.html.erb
<%= link_to sanitize("&larr; Zurück zu Räume"), rooms_path %>
<div class="container-title">
  <h1> Raum bearbeiten </h1>
</div>
<div class="container-content">
  <%= turbo_frame_tag @room do %>
    <div class="card">
      <%= render "form", room: @room %>
    </div>
  <% end %>
</div>

rails_app/app/views/rooms/index.html.erb
<%= turbo_stream_from "rooms" %>
<div class="container-title">
  <h1>Räume</h1>
  <% if policy(Room.new).create? %>
    <%= link_to icon("fa-solid", "plus", "Raum hinzufügen", class: "fa-1x"),
                new_room_path,
                class: "btn btn-green",
                data: { turbo_frame: dom_id(Room.new) }%>
  <% end %>
</div>
<div class="container-content">
  <%= turbo_frame_tag Room.new %>
  <%= turbo_frame_tag "rooms" do %>
    <%= render "rooms/empty_state" %>
    <%= render @rooms %>
  <% end %>
</div>

rails_app/app/views/rooms/new.html.erb
<%= link_to sanitize("&larr; Zurück zu Räume"), rooms_path %>
<div class="container-title">
  <h1> Neue Raum </h1>
</div>
<%= turbo_frame_tag @room do %>
  <div class="card">
  <%= render "form", room: @room %>
  </div>
<% end %>

rails_app/app/views/rooms/show.html.erb
<%= link_to sanitize("&larr; Zurück zu Räume"), rooms_path %>
<div class="container-title">
  To be announced.... Watch some kitten videos instead!

</div>

rails_app/app/views/rooms/update.turbo_stream.erb
<%= turbo_stream.replace @room %>
<%= render_turbo_stream_flash_messages %>